# https://github.com/github/licensed/blob/master/docs/configuration.md
sources:
  npm: true

allowed:
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - mit
  - cc0-1.0
  - unlicense

reviewed:
  npm:
  - '@actions/http-client' # Have MIT but is wrongly listed as "other"
