# https://github.com/github/licensed/blob/master/docs/commands.md
name: "Licensed"

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'

jobs:
  License:
    name: Valid licenses
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # 0 indicates all history for all branches and tags
        #ref: ${{github.ref}} # checkout branch not SHA
    - name: Install dependencies
      run: |
        sudo apt-get install cmake pkg-config
    - name: Setup Licensed
      uses: jonabc/setup-licensed@v1 # https://github.com/marketplace/actions/setup-github-licensed
      with:
        version: 2.x
    - name: Install build dependencies
      run: |
        sudo npm install --global npm
        npm install
    - name: Licensed
      id: licensed
      run: |
        licensed version
        licensed list -c .licensed.yml
        licensed cache -c .licensed.yml
        licensed status -c .licensed.yml
      # uses: jonabc/licensed-ci@v1 # https://github.com/marketplace/actions/licensed-ci, runs https://github.com/github/licensed
      # with:
      #   github_token: ${{ secrets.GITHUB_TOKEN }}
      #   workflow: branch
