name: "Licensed"

on:
  push:
    branches:
    - 'main'
    - 'releases/*'
  pull_request:
    branches:
    - 'main'

jobs:
  License:
    name: Valid licenses
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # 0 indicates all history for all branches and tags
    - name: Setup Licensed
      uses: jonabc/setup-licensed@v1 # https://github.com/marketplace/actions/setup-github-licensed
      with:
        version: 2.x
    - name: Install dependencies
      run: |
        npm install
    - name: Licensed
      id: licensed
      uses: jonabc/licensed-ci@v1 # https://github.com/marketplace/actions/licensed-ci, runs https://github.com/github/licensed
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: branch
