name: "Licensed"

on:
  push:
    branches:
    - 'releases/*'

jobs:
  License:
    name: Check licenses
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jonabc/setup-licensed@v1 # https://github.com/marketplace/actions/setup-github-licensed
      with:
        version: 2.x
    - run: npm install # Install your projects dependencies
    - id: licensed
      uses: jonabc/licensed-ci@v1 # https://github.com/marketplace/actions/licensed-ci, runs https://github.com/github/licensed
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: branch
