name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  Build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node: [ '12', '14' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node v${{ matrix.node }}
        uses: actions/setup-node@v2 # https://github.com/actions/setup-node
        with:
          node-version: ${{ matrix.node }}
      - run: |
          npm install
      - run: |
          npm run all

  Test: # run just the tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node: [ '12', '14' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node v${{ matrix.node }}
        uses: actions/setup-node@v2 # https://github.com/actions/setup-node
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run build
      - run: npm test

  Execute: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node: [ '12', '14' ]
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Setup node v${{ matrix.node }}
        uses: actions/setup-node@v2 # https://github.com/actions/setup-node
        with:
          node-version: ${{ matrix.node }}
      - name: Execute action Relabeler
        uses: ./
        with:
          milliseconds: 1200
          repoToken: ${{ secrets.GITHUB_TOKEN }}
